import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion } from 'framer-motion';
import { Bell, Trophy, X, User, ChevronUp, Medal, LogOut, Crosshair, Shield, Thermometer, Gauge, MapPin } from 'lucide-react';
import './styles.css';
import { achievements, computeAchievementUnlocks, timeBucket, twoHoursRemainingMs, todayKey } from './rules.js';

const API = '/api';
const authHeaders = () => ({ 'Content-Type': 'application/json', Authorization: 'Bearer ' + (localStorage.getItem('bust_token') || '') });
async function api(path, options={}) {
  const res = await fetch(API + path, { ...options, headers: { ...authHeaders(), ...(options.headers||{}) }});
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.error || 'Request failed');
  return data;
}
function avatar(seed) { return `https://api.dicebear.com/9.x/identicon/svg?seed=${encodeURIComponent(seed || 'bust')}&backgroundColor=0a0a0b&rowColor=ff5e00,f5f0e8`; }
function fmt(ts) { return new Date(ts).toLocaleString([], { month:'short', day:'numeric', hour:'numeric', minute:'2-digit' }); }
function rankForDay(bust, busts) { const d = new Date(bust.timestamp).toDateString(); const list = busts.filter(b=>new Date(b.timestamp).toDateString()===d).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp)); return list.findIndex(b=>b.id===bust.id)+1 || '—'; }

function Login({ onAuthed }) {
  const [mode, setMode] = useState('login'); const [form,setForm]=useState({username:'',password:'',inviteCode:''}); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(e){ e.preventDefault(); setBusy(true); setError(''); try { const data = await api(mode==='login'?'/login':'/signup',{method:'POST',body:JSON.stringify(form)}); localStorage.setItem('bust_token',data.token); onAuthed(data.user); } catch(err){ setError(err.message); } finally{ setBusy(false); }}
  return <main className="login-shell"><section className="auth-card mf-frame"><div className="mf-kicker">PRIVATE SIGNAL // COMPONENT BAY</div><h1>BUST</h1><p className="auth-copy">A real-time satirical pressure logging terminal for a trusted crew.</p><form onSubmit={submit}><label>Username<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} autoFocus /></label><label>Password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} /></label>{mode==='signup'&&<label>invite-code<input value={form.inviteCode} onChange={e=>setForm({...form,inviteCode:e.target.value})} /></label>}<button className="mf-button" disabled={busy}>{busy?'TRANSMITTING…':mode==='login'?'ENTER BAY':'CREATE OPERATOR'}</button></form>{error&&<div className="error">{error}</div>}<button className="text-link" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Need access? Register with invite-code.':'Already cleared? Login.'}</button></section></main>
}

function App(){ const [user,setUser]=useState(null); const [boot,setBoot]=useState(true); useEffect(()=>{api('/me').then(d=>setUser(d.user)).catch(()=>{}).finally(()=>setBoot(false))},[]); if(boot) return <div className="boot">UNPACKING BUST BAY…</div>; return user?<Dashboard user={user} setUser={setUser}/>:<Login onAuthed={setUser}/> }

function Dashboard({user,setUser}){ const [busts,setBusts]=useState([]),[users,setUsers]=useState([]),[unlocks,setUnlocks]=useState([]); const [overlay,setOverlay]=useState(null),[selected,setSelected]=useState(null),[phase,setPhase]=useState('idle'),[note,setNote]=useState(''),[pendingCtx,setPendingCtx]=useState(null),[toasts,setToasts]=useState([]),[unread,setUnread]=useState(0); const bustRef=useRef([]); bustRef.current=busts;
  const remaining = twoHoursRemainingMs(user.last_bust_timestamp); const locked = remaining > 0 && phase==='idle';
  async function refresh(){ const d=await api('/dashboard'); setBusts(d.busts); setUsers(d.users); setUnlocks(d.achievements); }
  useEffect(()=>{ refresh(); const proto=location.protocol==='https:'?'wss':'ws'; const ws=new WebSocket(`${proto}://${location.host}/ws?token=${localStorage.getItem('bust_token')}`); ws.onmessage=e=>{ const msg=JSON.parse(e.data); if(msg.type==='bust'){ setBusts(prev=>[msg.bust,...prev.filter(b=>b.id!==msg.bust.id)]); setUsers(prev=>prev.map(u=>u.id===msg.bust.user_id?{...u,last_bust_timestamp:msg.bust.timestamp}:u)); setUnread(n=>n+1); setToasts(t=>[{id:crypto.randomUUID(),bust:msg.bust},...t]); if(Notification?.permission==='granted') new Notification(`${msg.bust.username} logged a BUST`, { body: msg.bust.note || 'Pressure event received.' }); }}; if(Notification?.permission==='default') Notification.requestPermission().catch(()=>{}); return()=>ws.close(); },[]);
  async function collectContext(){ let lat=null,long=null,temp_f=null,pressure=null,city='Unknown sector'; try{ const cached=JSON.parse(localStorage.getItem('bust_geo')||'null'); const pos=cached && Date.now()-cached.at<86400000 ? cached : await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(p=>res({lat:p.coords.latitude,long:p.coords.longitude,at:Date.now()}),rej,{timeout:6000})); localStorage.setItem('bust_geo',JSON.stringify(pos)); lat=pos.lat; long=pos.long; const w=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${long}&current=temperature_2m,surface_pressure&temperature_unit=fahrenheit`).then(r=>r.json()); temp_f=w.current?.temperature_2m ?? null; pressure=w.current?.surface_pressure ?? null; }catch{} return {lat,long,temp_f,pressure,city}; }
  async function startBust(){ if(locked || phase!=='idle') return; navigator.vibrate?.([35,45,70,65,100]); setPhase('charge'); setPendingCtx(await collectContext()); setTimeout(()=>{navigator.vibrate?.([180,60,220,80,300]); setPhase('explode');},1400); setTimeout(()=>setPhase('note'),5900); }
  async function commitBust(){ const payload={note,...pendingCtx}; const data=await api('/bust',{method:'POST',body:JSON.stringify(payload)}); const current=[data.bust,...bustRef.current]; const newOnes=computeAchievementUnlocks(data.bust.user_id,current,unlocks); if(newOnes.length){ const saved=await api('/achievements',{method:'POST',body:JSON.stringify({types:newOnes})}); setUnlocks(saved.achievements); }
    setUser({...user,last_bust_timestamp:data.bust.timestamp}); setNote(''); setPendingCtx(null); setPhase('idle'); setSelected(data.bust); }
  const analytics=useMemo(()=>buildAnalytics(busts,users,user),[busts,users,user]);
  return <main className={`dash ${phase==='charge'?'charging':''} ${phase==='explode'?'detonating':''}`}><GridBg/><header><button className="profile-chip" onClick={()=>setOverlay('profile')}><img src={avatar(user.avatar_seed)}/><span>{user.username}</span></button><div className="top-actions"><button className="icon-btn" onClick={()=>{setOverlay('alerts');setUnread(0)}}><Bell/>{unread>0&&<b>{unread}</b>}</button><button className="icon-btn" onClick={()=>setOverlay('trophy')}><Trophy/></button></div></header><section className="button-stage">{locked?<CooldownScene/>:<BustButton phase={phase} onClick={startBust}/>}</section><button className="drawer-handle" onClick={()=>setOverlay('analytics')}><ChevronUp/> ANALYTICS BAY</button><Toasts toasts={toasts} setToasts={setToasts} onOpen={setSelected}/><AnimatePresence>{phase==='note'&&<NoteModal note={note} setNote={setNote} onCommit={commitBust}/>} {overlay&&<Overlay title={overlayTitle(overlay)} onClose={()=>setOverlay(null)}>{overlay==='profile'&&<Profile user={user} setUser={setUser}/>} {overlay==='alerts'&&<Alerts busts={busts} onOpen={setSelected}/>} {overlay==='analytics'&&<Analytics data={analytics} busts={busts} onOpen={setSelected}/>} {overlay==='trophy'&&<TrophyCabinet unlocks={unlocks}/>}</Overlay>} {selected&&<Detail bust={selected} all={busts} onClose={()=>setSelected(null)}/>}</AnimatePresence>{phase==='explode'&&<Explosion/>}</main> }
function GridBg(){ return <div className="grid-bg"/> }
function BustButton({phase,onClick}){ return <motion.button className="bust-button" disabled={phase!=='idle'} onClick={onClick} animate={phase==='charge'?{scale:[1,1.04,.98,1.06,1],rotate:[0,-2,2,-3,3,0]}:{}} transition={{duration:.22,repeat:phase==='charge'?Infinity:0}}><span>{phase==='charge'?'HOLD… building pressure':'BUST'}</span><em>{phase==='idle'?'PRESSURE RELEASE CONTROL':'CHAMBER CRITICAL'}</em>{phase==='charge'&&<><i/><i/><i/></>}</motion.button> }
function Explosion(){ return <div className="explosion">{Array.from({length:90}).map((_,i)=><span key={i} style={{'--x':`${Math.random()*120-60}vw`,'--y':`${Math.random()*100-50}vh`,'--d':`${Math.random()*1.6}s`}}/>)}<div className="milk-sheet"/></div> }
function NoteModal({note,setNote,onCommit}){ return <motion.div className="note-pop mf-frame" initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} exit={{opacity:0}}><h2>CAPTURE BUST NOTE</h2><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional field report…"/><button className="mf-button" onClick={onCommit}>COMMIT TO LEDGER</button></motion.div> }
function CooldownScene(){ return <div className="cooldown mf-frame"><div className="iso"><div className="fallen">BUST</div><div className="puddle"/></div><h2>BUTTON OFFLINE</h2><p>Silent 2-hour cooldown enforced from database timestamp. The puddle dries when access returns.</p></div> }
function Overlay({title,onClose,children}){ return <motion.section className="overlay" initial={{y:'100%'}} animate={{y:0}} exit={{y:'100%'}}><button className="close" onClick={onClose}><X/></button><div className="overlay-head"><span className="mf-kicker">MISSION FORGE // FULL BLEED</span><h1>{title}</h1></div>{children}</motion.section> }
function Detail({bust,all,onClose}){ return <motion.div className="detail-back" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="detail mf-frame"><button className="close" onClick={onClose}><X/></button><img src={avatar(bust.avatar_seed)}/><h2>{bust.username}</h2><p>{fmt(bust.timestamp)} · {bust.time_bucket}</p><blockquote>{bust.note || 'No note logged.'}</blockquote><div className="metric-grid"><Metric icon={<Thermometer/>} label="TEMP" value={bust.temp_f?`${Math.round(bust.temp_f)}°F`:'—'}/><Metric icon={<Gauge/>} label="PRESSURE" value={bust.pressure?`${Math.round(bust.pressure)} hPa`:'—'}/><Metric icon={<MapPin/>} label="LOCATION" value={bust.city||'Unknown'}/><Metric icon={<Medal/>} label="DAY RANK" value={`#${rankForDay(bust,all)}`}/></div></div></motion.div> }
function Metric({icon,label,value}){return <div className="metric">{icon}<small>{label}</small><strong>{value}</strong></div>}
function Profile({user,setUser}){ return <div className="panel-grid"><div className="profile-big mf-frame"><img src={avatar(user.avatar_seed)}/><h2>{user.username}</h2><p>Operator since {new Date(user.created_at).toLocaleDateString()}</p><button className="mf-button" onClick={()=>{localStorage.removeItem('bust_token');setUser(null)}}><LogOut/> LOG OUT</button></div></div> }
function Alerts({busts,onOpen}){ return <div className="feed two-col">{busts.map(b=><BustCard key={b.id} b={b} onOpen={onOpen}/>)}</div> }
function BustCard({b,onOpen}){ return <button className="bust-card mf-frame" onClick={()=>onOpen(b)}><img src={avatar(b.avatar_seed)}/><div><strong>{b.username}</strong><span>{fmt(b.timestamp)} · {b.time_bucket}</span><p>{b.note || 'Pressure spike recorded.'}</p></div></button> }
function Analytics({data,busts,onOpen}){ return <div className="analytics"><div className="stat-strip">{data.stats.map(s=><div className="stat mf-frame" key={s.label}><span>{s.label}</span><strong>{s.value}</strong></div>)}</div><section className="analytics-grid"><div className="mf-frame module"><h2>Leaderboard</h2>{data.leaderboard.map((u,i)=><div className="leader" key={u.id}><span>#{i+1}</span><img src={avatar(u.avatar_seed)}/><b>{u.username}</b><em>{u.count} // {['Cream of the Crop','Daily Dripper','Pressure Adept','Puddle Scout'][i]||'Bay Operator'}</em></div>)}</div><div className="mf-frame module"><h2>Weekly Volume</h2><div className="bars">{data.week.map(d=><div key={d.label}><i style={{height:`${Math.max(8,d.count*22)}px`}}/><span>{d.label}</span></div>)}</div></div><div className="mf-frame module"><h2>Heatmap</h2><div className="heat">{data.heat.map((v,i)=><span key={i} style={{opacity:.15+Math.min(v,5)*.17}} title={`${v}`}/>)}</div></div><div className="mf-frame module"><h2>Environment Scatter</h2><div className="scatter">{data.scatter.map((p,i)=><span key={i} style={{left:`${p.x}%`,bottom:`${p.y}%`}}/>)}</div></div></section><h2 className="section-title">Today’s Feed</h2><div className="feed two-col">{busts.filter(b=>todayKey(b.timestamp)===todayKey()).map(b=><BustCard key={b.id} b={b} onOpen={onOpen}/>)}</div></div> }
function TrophyCabinet({unlocks}){ const set=new Set(unlocks.map(a=>a.achievement_type)); return <div className="trophy-grid">{achievements.map(a=><div className={`trophy mf-frame ${set.has(a.id)?'won':'locked'}`} key={a.id}><Shield/><h2>{a.name}</h2><p>{a.desc}</p></div>)}</div> }
function Toasts({toasts,setToasts,onOpen}){ return <div className="toasts">{toasts.map(t=><div className="toast mf-frame" key={t.id} onClick={()=>onOpen(t.bust)}><button onClick={(e)=>{e.stopPropagation();setToasts(x=>x.filter(y=>y.id!==t.id))}}>×</button><b>{t.bust.username} BUSTED</b><span>{t.bust.note||'Open detail card.'}</span></div>)}</div> }
function overlayTitle(o){return {profile:'OPERATOR PROFILE',alerts:'ALERT FEED',analytics:'ANALYTICS DRAWER',trophy:'TROPHY CABINET'}[o]}
function buildAnalytics(busts,users,user){ const counts=users.map(u=>({...u,count:busts.filter(b=>b.user_id===u.id).length})).sort((a,b)=>b.count-a.count); const today=busts.filter(b=>todayKey(b.timestamp)===todayKey()).length; const stats=[{label:'GROUP BUSTS',value:busts.length},{label:'ACTIVE PLAYERS',value:users.length},{label:'TODAY',value:today},{label:'YOUR RANK',value:'#'+(counts.findIndex(u=>u.id===user.id)+1||'—')}]; const week=Array.from({length:7}).map((_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));return {label:d.toLocaleDateString([],{weekday:'short'}),count:busts.filter(b=>new Date(b.timestamp).toDateString()===d.toDateString()).length}}); const heat=Array.from({length:24*7},(_,i)=>busts.filter(b=>new Date(b.timestamp).getDay()*24+new Date(b.timestamp).getHours()===i).length); const temps=busts.filter(b=>b.temp_f&&b.pressure); const scatter=temps.map(b=>({x:Math.max(0,Math.min(100,(b.temp_f-20)/90*100)),y:Math.max(0,Math.min(100,(b.pressure-950)/100*100))})); return {stats,leaderboard:counts,week,heat,scatter}; }
createRoot(document.getElementById('root')).render(<App/>);

