import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion } from 'framer-motion';
import { Activity, AlarmClock, BadgeCheck, Bell, CalendarDays, ChevronUp, Clock3, Crown, Flame, Gauge, LogOut, MapPin, MapPinned, Medal, Moon, NotebookPen, Repeat2, Shield, Snowflake, Sparkles, Sun, Sunrise, Thermometer, Trophy, X } from 'lucide-react';
import './styles.css';
import { achievements, computeAchievementUnlocks, deriveAllTimeRecords, deriveProgressionSummary, progressionCatalog, timeBucket, twoHoursRemainingMs, todayKey } from './rules.js';

const API = '/api';
const authHeaders = () => ({ 'Content-Type': 'application/json', Authorization: 'Bearer ' + (localStorage.getItem('bust_token') || '') });
async function api(path, options={}) {
  const res = await fetch(API + path, { ...options, headers: { ...authHeaders(), ...(options.headers||{}) }});
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.error || 'Request failed');
  return data;
}
function avatar(seed) { return `https://api.dicebear.com/9.x/identicon/svg?seed=${encodeURIComponent(seed || 'bust')}&backgroundColor=0a0a0b&rowColor=ff5e00,f5f0e8`; }
function fmt(ts) { return new Date(ts).toLocaleString([], { month:'short', day:'numeric', hour:'numeric', minute:'2-digit' }); }
function rankForDay(bust, busts) { const d = new Date(bust.timestamp).toDateString(); const list = busts.filter(b=>new Date(b.timestamp).toDateString()===d).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp)); return list.findIndex(b=>b.id===bust.id)+1 || '—'; }

function Login({ onAuthed }) {
  const [mode, setMode] = useState('login'); const [form,setForm]=useState({username:'',password:'',inviteCode:''}); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(e){ e.preventDefault(); setBusy(true); setError(''); try { const data = await api(mode==='login'?'/login':'/signup',{method:'POST',body:JSON.stringify(form)}); localStorage.setItem('bust_token',data.token); onAuthed(data.user); } catch(err){ setError(err.message); } finally{ setBusy(false); }}
  return <main className="login-shell"><section className="auth-card mf-frame"><div className="mf-kicker">PRIVATE SIGNAL</div><h1>BUST</h1><p className="auth-copy">A real-time satirical pressure logging terminal for a trusted crew.</p><form onSubmit={submit}><label>Username<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} autoFocus /></label><label>Password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} /></label>{mode==='signup'&&<label>invite-code<input value={form.inviteCode} onChange={e=>setForm({...form,inviteCode:e.target.value})} /></label>}<button className="mf-button" disabled={busy}>{busy?'TRANSMITTING…':mode==='login'?'ENTER BAY':'CREATE OPERATOR'}</button></form>{error&&<div className="error">{error}</div>}<button className="text-link" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Need access? Register with invite-code.':'Already cleared? Login.'}</button></section></main>
}

function App(){ const [user,setUser]=useState(null); const [boot,setBoot]=useState(true); useEffect(()=>{api('/me').then(d=>setUser(d.user)).catch(()=>{}).finally(()=>setBoot(false))},[]); if(boot) return <div className="boot">UNPACKING BUST BAY…</div>; return user?<Dashboard user={user} setUser={setUser}/>:<Login onAuthed={setUser}/> }

function Dashboard({user,setUser}){ const [busts,setBusts]=useState([]),[users,setUsers]=useState([]),[unlocks,setUnlocks]=useState([]); const [overlay,setOverlay]=useState(null),[selected,setSelected]=useState(null),[phase,setPhase]=useState('idle'),[note,setNote]=useState(''),[pendingCtx,setPendingCtx]=useState(null),[toasts,setToasts]=useState([]),[unread,setUnread]=useState(0),[badgeToast,setBadgeToast]=useState(null); const bustRef=useRef([]); bustRef.current=busts;
  const remaining = twoHoursRemainingMs(user.last_bust_timestamp); const locked = remaining > 0 && phase==='idle';
  async function refresh(){ const d=await api('/dashboard'); setBusts(d.busts); setUsers(d.users); setUnlocks(d.achievements); }
  useEffect(()=>{ refresh(); const proto=location.protocol==='https:'?'wss':'ws'; const ws=new WebSocket(`${proto}://${location.host}/ws?token=${localStorage.getItem('bust_token')}`); ws.onmessage=e=>{ const msg=JSON.parse(e.data); if(msg.type==='bust'){ setBusts(prev=>[msg.bust,...prev.filter(b=>b.id!==msg.bust.id)]); setUsers(prev=>prev.map(u=>u.id===msg.bust.user_id?{...u,last_bust_timestamp:msg.bust.timestamp}:u)); setUnread(n=>n+1); setToasts(t=>[{id:crypto.randomUUID(),bust:msg.bust},...t]); if(Notification?.permission==='granted') new Notification(`${msg.bust.username} logged a BUST`, { body: msg.bust.note || 'Pressure event received.' }); }}; if(Notification?.permission==='default') Notification.requestPermission().catch(()=>{}); return()=>ws.close(); },[]);
  async function collectContext(){ let lat=null,long=null,temp_f=null,pressure=null,city='Unknown sector'; try{ const cached=JSON.parse(localStorage.getItem('bust_geo')||'null'); const pos=cached && Date.now()-cached.at<86400000 ? cached : await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(p=>res({lat:p.coords.latitude,long:p.coords.longitude,at:Date.now()}),rej,{timeout:6000})); localStorage.setItem('bust_geo',JSON.stringify(pos)); lat=pos.lat; long=pos.long; const w=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${long}&current=temperature_2m,surface_pressure&temperature_unit=fahrenheit`).then(r=>r.json()); temp_f=w.current?.temperature_2m ?? null; pressure=w.current?.surface_pressure ?? null; }catch{} return {lat,long,temp_f,pressure,city}; }
  async function startBust(){ if(locked || phase!=='idle') return; navigator.vibrate?.([35,45,70,65,100]); setPhase('charge'); setPendingCtx(await collectContext()); setTimeout(()=>{navigator.vibrate?.([180,60,220,80,300]); setPhase('explode');},1400); setTimeout(()=>setPhase('note'),5900); }
  async function commitBust(){ const payload={note,...pendingCtx}; const data=await api('/bust',{method:'POST',body:JSON.stringify(payload)}); const current=[data.bust,...bustRef.current]; const newOnes=computeAchievementUnlocks(data.bust.user_id,current,unlocks); if(newOnes.length){ const saved=await api('/achievements',{method:'POST',body:JSON.stringify({types:newOnes})}); setUnlocks(saved.achievements); const featured=achievements.find(a=>a.id===newOnes[0]); setBadgeToast(featured); setTimeout(()=>setBadgeToast(null),5200); }
    setUser({...user,last_bust_timestamp:data.bust.timestamp}); setNote(''); setPendingCtx(null); setPhase('idle'); setSelected(data.bust); }
  const analytics=useMemo(()=>buildAnalytics(busts,users,user),[busts,users,user]);
  return <main className={`dash ${locked?'cooldown-mode':''} ${phase==='charge'?'charging':''} ${phase==='explode'?'detonating':''}`}><GridBg/>{locked&&<CooldownGoop/>}<header><button className="profile-chip" onClick={()=>setOverlay('profile')}><img src={avatar(user.avatar_seed)}/><span>{user.username}</span></button><div className="top-actions"><button className="icon-btn" onClick={()=>{setOverlay('alerts');setUnread(0)}}><Bell/>{unread>0&&<b>{unread}</b>}</button><button className="icon-btn trophy-action" onClick={()=>setOverlay('trophy')}><Trophy/><small>{deriveProgressionSummary(user.id,unlocks).totalUnlocked}/{progressionCatalog.length*3}</small></button></div></header><section className="button-stage">{locked?<CooldownScene/>:<BustButton phase={phase} onClick={startBust}/>}</section><button className="drawer-handle" onClick={()=>setOverlay('analytics')}><ChevronUp/> ANALYTICS BAY</button><Toasts toasts={toasts} setToasts={setToasts} onOpen={setSelected}/><AnimatePresence>{badgeToast&&<BadgeToast key="badge-toast" badge={badgeToast}/>} {phase==='note'&&<NoteModal key="note-modal" note={note} setNote={setNote} onCommit={commitBust}/>} {overlay&&<Overlay key={`overlay-${overlay}`} title={overlayTitle(overlay)} onClose={()=>setOverlay(null)}>{overlay==='profile'&&<Profile user={user} setUser={setUser}/>} {overlay==='alerts'&&<Alerts busts={busts} onOpen={setSelected}/>} {overlay==='analytics'&&<Analytics data={analytics} busts={busts} onOpen={setSelected}/>} {overlay==='trophy'&&<TrophyCabinet unlocks={unlocks} user={user}/>}</Overlay>} {selected&&<Detail key={`detail-${selected.id}`} bust={selected} all={busts} onClose={()=>setSelected(null)}/>}</AnimatePresence>{phase==='explode'&&<Explosion/>}</main> }
function GridBg(){ return <div className="grid-bg"/> }
function BustButton({phase,onClick}){ return <motion.button className="bust-button" disabled={phase!=='idle'} onClick={onClick} animate={phase==='charge'?{scale:[1,1.07,.96,1.09,1],rotate:[0,-3,3,-5,5,0],filter:['hue-rotate(0deg)','hue-rotate(-16deg)','hue-rotate(0deg)']}:{}} transition={{duration:.18,repeat:phase==='charge'?Infinity:0}}><span>{phase==='charge'?'HOLD… building pressure':'BUST'}</span><em>{phase==='idle'?'PRESSURE RELEASE CONTROL':'CHAMBER CRITICAL'}</em><strong className="button-crack"/>{phase==='charge'&&<><i/><i/><i/><i/></>}</motion.button> }
function Explosion(){ const drops=Array.from({length:150}); const ropes=Array.from({length:18}); const shards=Array.from({length:42}); return <div className="explosion"><div className="blast-flash"/>{ropes.map((_,i)=><b className="goop-rope" key={`r${i}`} style={{'--l':`${Math.random()*100}%`,'--w':`${22+Math.random()*80}px`,'--h':`${38+Math.random()*70}vh`,'--d':`${Math.random()*.55}s`}}/>)}{drops.map((_,i)=><span className="milk-drop" key={`d${i}`} style={{'--x':`${Math.random()*150-75}vw`,'--y':`${Math.random()*120-60}vh`,'--s':`${7+Math.random()*28}px`,'--d':`${Math.random()*1.1}s`}}/>)}{shards.map((_,i)=><i className="button-shard" key={`s${i}`} style={{'--x':`${Math.random()*120-60}vw`,'--y':`${Math.random()*100-50}vh`,'--r':`${Math.random()*900-450}deg`,'--d':`${Math.random()*.6}s`}}/>)}<div className="milk-sheet"/><div className="screen-splatter"/></div> }
function CooldownGoop(){ return <div className="cooldown-goop" aria-hidden="true"><span/><span/><span/><span/><span/><span/><span/><span/></div> }
function NoteModal({note,setNote,onCommit}){ return <motion.div className="note-pop mf-frame" initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} exit={{opacity:0}}><h2>CAPTURE BUST NOTE</h2><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional field report…"/><button className="mf-button" onClick={onCommit}>COMMIT TO LEDGER</button></motion.div> }
function CooldownScene(){ return <div className="cooldown-scene" aria-label="BUST cooldown scene"><div className="iso"><div className="fallen">Busted</div><div className="puddle"/><div className="puddle-splash one"/><div className="puddle-splash two"/></div></div> }
const iconMap={Activity,AlarmClock,Clock3,Sparkles,Repeat2,Moon,Sun,Sunrise,Flame,Snowflake,Gauge,NotebookPen,BadgeCheck,CalendarDays,MapPinned,Crown,Medal,Trophy,Shield};
function BadgeIcon({name}){ const Icon=iconMap[name]||Shield; return <Icon/> }
function BadgeToast({badge}){ if(!badge) return null; return <motion.div className="badge-toast mf-frame" initial={{opacity:0,y:-22,scale:.92}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-22}}><div className="badge-medal" style={{'--badge':badge.accent}}><BadgeIcon name={badge.icon}/></div><div><span>ACHIEVEMENT UNLOCKED</span><h2>{badge.name}</h2><p>{badge.tier.toUpperCase()} · {badge.points} XP</p></div></motion.div> }
function Overlay({title,onClose,children}){ return <motion.section className="overlay" initial={{y:'100%'}} animate={{y:0}} exit={{y:'100%'}}><button className="close" onClick={onClose}><X/></button><div className="overlay-head"><span className="mf-kicker">FULL BLEED</span><h1>{title}</h1></div>{children}</motion.section> }
function Detail({bust,all,onClose}){ return <motion.div className="detail-back" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="detail mf-frame"><button className="detail-close" onClick={onClose} aria-label="Close detail"><X/></button><img src={avatar(bust.avatar_seed)}/><h2>{bust.username}</h2><p>{fmt(bust.timestamp)} · {bust.time_bucket}</p><blockquote>{bust.note || 'No note logged.'}</blockquote><div className="metric-grid"><Metric icon={<Thermometer/>} label="TEMP" value={bust.temp_f?`${Math.round(bust.temp_f)}°F`:'—'}/><Metric icon={<Gauge/>} label="PRESSURE" value={bust.pressure?`${Math.round(bust.pressure)} hPa`:'—'}/><Metric icon={<MapPin/>} label="LOCATION" value={bust.city||'Unknown'}/><Metric icon={<Medal/>} label="DAY RANK" value={`#${rankForDay(bust,all)}`}/></div></div></motion.div> }
function Metric({icon,label,value}){return <div className="metric">{icon}<small>{label}</small><strong>{value}</strong></div>}
function Profile({user,setUser}){ return <div className="panel-grid"><div className="profile-big mf-frame"><img src={avatar(user.avatar_seed)}/><h2>{user.username}</h2><p>Operator since {new Date(user.created_at).toLocaleDateString()}</p><button className="mf-button" onClick={()=>{localStorage.removeItem('bust_token');setUser(null)}}><LogOut/> LOG OUT</button></div></div> }
function Alerts({busts,onOpen}){ return <div className="feed two-col">{busts.map(b=><BustCard key={b.id} b={b} onOpen={onOpen}/>)}</div> }
function BustCard({b,onOpen}){ return <button className="bust-card mf-frame" onClick={()=>onOpen(b)}><img src={avatar(b.avatar_seed)}/><div><strong>{b.username}</strong><span>{fmt(b.timestamp)} · {b.time_bucket}</span><p>{b.note || 'Pressure spike recorded.'}</p></div></button> }
function Analytics({data,busts,onOpen}){ const today=busts.filter(b=>todayKey(b.timestamp)===todayKey()); return <div className="analytics"><div className="stat-strip">{data.stats.map(s=><div className="stat mf-frame" key={s.label}><span>{s.label}</span><strong>{s.value}</strong><small>{s.hint}</small></div>)}</div><section className="analytics-grid"><div className="mf-frame module leaderboard-module"><h2>Leaderboard</h2><p>Ranked avatar tiles with satirical titles and all-time volume.</p>{data.leaderboard.length?data.leaderboard.map((u,i)=><div className="leader" key={u.id}><span>#{i+1}</span><img src={avatar(u.avatar_seed)}/><b>{u.username}</b><em>{u.count} // {['Cream of the Crop','Daily Dripper','Pressure Adept','Puddle Scout'][i]||'Bay Operator'}</em></div>):<EmptyState text="No operators have logged yet."/>}</div><div className="mf-frame module chart-module"><h2>Weekly Volume</h2><p>Day-over-day ledger intensity.</p><div className="bars">{data.week.map(d=><div key={d.label}><i style={{height:`${Math.max(8,d.count*22)}px`}}/><strong>{d.count}</strong><span>{d.label}</span></div>)}</div></div><div className="mf-frame module chart-module"><h2>Heatmap</h2><p>24-hour activity by day of week.</p><div className="heat-wrap"><div className="heat-axis">{['S','M','T','W','T','F','S'].map((d,i)=><b key={i}>{d}</b>)}</div><div className="heat">{data.heat.map((v,i)=><span key={i} style={{opacity:.12+Math.min(v,5)*.18}} title={`${v} events`}/>)}</div></div></div><div className="mf-frame module chart-module"><h2>Environment Scatter</h2><p>Temperature versus barometric pressure.</p><div className="scatter"><small className="axis-y">Pressure</small><small className="axis-x">Temp °F</small>{data.scatter.map((p,i)=><span key={i} style={{left:`${p.x}%`,bottom:`${p.y}%`}}/>)}</div></div></section><section className="records-grid">{data.records.map(r=><div className="record-card mf-frame" key={r.id}><BadgeIcon name={r.icon}/><span>{r.label}</span><strong>{r.value}</strong><p>{r.detail}</p></div>)}</section><h2 className="section-title">Today’s Feed</h2><div className="feed two-col">{today.length?today.map(b=><BustCard key={b.id} b={b} onOpen={onOpen}/>):<EmptyState text="No busts in the current 24-hour window."/>}</div></div> }
function TrophyCabinet({unlocks,user}){ const set=new Set(unlocks.filter(a=>a.user_id===user.id).map(a=>a.achievement_type)); const summary=deriveProgressionSummary(user.id,unlocks); return <div className="achievement-hall"><div className="trophy-summary mf-frame"><Trophy/><div><span>ACHIEVEMENT HALL</span><strong>{summary.totalUnlocked}/{summary.totalItems} progression items · {summary.totalPoints} XP</strong></div></div><section className="progression-radar mf-frame"><div><span className="mf-kicker">TROPHY FORGE</span><h2>Achievements build into badges, badges build into trophies.</h2><p>Each vertical track has three escalating stages. Smaller unlocks stay useful because they visibly fill the trophy path.</p></div><div className="ring-chart" style={{'--pct':`${Math.max(4,Math.round(summary.totalUnlocked/summary.totalItems*100))}%`}}><strong>{Math.round(summary.totalUnlocked/summary.totalItems*100)}%</strong><span>complete</span></div></section><div className="achievement-tracks">{summary.tracks.map(track=><section className="track-card mf-frame" key={track.id} style={{'--badge':track.accent}}><header><div className="track-icon"><BadgeIcon name={track.icon}/></div><div><span>{track.unlocked}/{track.total} unlocked</span><h2>{track.name}</h2><p>{track.desc}</p></div></header><div className="track-meter"><i style={{width:`${track.percent}%`}}/></div><div className="stage-ladder">{track.stages.map((item,index)=>{const active=index<track.unlocked; return <div className={`stage-node ${active?'won':'locked'} ${item.kind}`} key={item.id}><div className="badge-medal" style={{'--badge':item.accent}}><BadgeIcon name={item.icon}/></div><span>{item.kind} · {item.goal}x</span><h3>{item.name}</h3><p>{item.desc}</p></div>})}</div></section>)}</div><h2 className="section-title trophy-archive-title">Legacy + Bonus Badges</h2><div className="trophy-grid compact">{achievements.filter(a=>a.track==='legacy').map(a=><div className={`trophy mf-frame ${set.has(a.id)?'won':'locked'} ${a.tier}`} style={{'--badge':a.accent}} key={a.id}><div className="badge-medal"><BadgeIcon name={a.icon}/></div><span>{a.kind} · {a.points} XP</span><h2>{a.name}</h2><p>{a.desc}</p></div>)}</div></div> }
function EmptyState({text}){ return <div className="empty-state"><Sparkles/><span>{text}</span></div> }
function Toasts({toasts,setToasts,onOpen}){ return <div className="toasts">{toasts.map(t=><div className="toast mf-frame" key={t.id} onClick={()=>onOpen(t.bust)}><button onClick={(e)=>{e.stopPropagation();setToasts(x=>x.filter(y=>y.id!==t.id))}}>×</button><b>{t.bust.username} BUSTED</b><span>{t.bust.note||'Open detail card.'}</span></div>)}</div> }
function overlayTitle(o){return {profile:'OPERATOR PROFILE',alerts:'ALERT FEED',analytics:'ANALYTICS DRAWER',trophy:'TROPHY CABINET'}[o]}
function buildAnalytics(busts,users,user){ const counts=users.map(u=>({...u,count:busts.filter(b=>b.user_id===u.id).length})).sort((a,b)=>b.count-a.count); const today=busts.filter(b=>todayKey(b.timestamp)===todayKey()).length; const rank=counts.findIndex(u=>u.id===user.id)+1; const stats=[{label:'GROUP BUSTS',value:busts.length,hint:'all-time ledger'},{label:'ACTIVE PLAYERS',value:users.length,hint:'registered operators'},{label:'TODAY',value:today,hint:'current local day'},{label:'YOUR RANK',value:rank>0?'#'+rank:'—',hint:'daily pressure index'}]; const week=Array.from({length:7}).map((_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));return {label:d.toLocaleDateString([],{weekday:'short'}),count:busts.filter(b=>new Date(b.timestamp).toDateString()===d.toDateString()).length}}); const heat=Array.from({length:24*7},(_,i)=>busts.filter(b=>new Date(b.timestamp).getDay()*24+new Date(b.timestamp).getHours()===i).length); const temps=busts.filter(b=>b.temp_f&&b.pressure); const scatter=temps.map(b=>({x:Math.max(0,Math.min(100,(b.temp_f-20)/90*100)),y:Math.max(0,Math.min(100,(b.pressure-950)/100*100))})); const records=deriveAllTimeRecords(busts); return {stats,leaderboard:counts,week,heat,scatter,records}; }
createRoot(document.getElementById('root')).render(<App/>);

